<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="ST00_Sequence" Id="{025350f4-7dcb-4f6b-a07b-6c138f0e63d1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM ST00_Sequence
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ST00_Sequence">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>