<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="DoorLock" Id="{9310e70f-f938-4312-bff5-999802aba96f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM DoorLock
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="DoorLock">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>